version: "3.9"
services:
  shorthand:
    build: ${AST_BUILD}
    env_file: .env
    stdin_open: true
    tty: true
    #network_mode: "host"
    extra_hosts:
      - "blog.cocajola.xyz:23.50.63.25"
  grid:
    image: "selenium/standalone-chrome"
    env_file: .env
    ports:
      - "4444:4444"
      # Switch on 7900 if SE_START_XVFB=true 
      #- "7900:7900"
    shm_size: "2gb"
    extra_hosts:
      - "blog.cocajola.xyz:23.50.63.25"