version: "3.9"
services:
  shorthand:
    build: .
    env_file: .env
    stdin_open: true
    tty: true
    extra_hosts:
      - "blog.cocajola.xyz:23.50.63.25"
  grid:
    image: "selenium/standalone-chrome"
    env_file: .env
    ports:
      - "4444:4444"
      # Switch on 7900 if SE_START_XVFB=true 
      #- "7900:7900"
    shm_size: "2gb"
    extra_hosts:
      - "blog.cocajola.xyz:23.50.63.25"

# docker run -d -p 4444:4444 -p 7900:7900 -e SE_START_XVFB=false -e SE_NODE_OVERRIDE_MAX_SESSIONS=true -e SE_NODE_MAX_SESSIONS=4 --shm-size="2g" --name grid selenium/standalone-chrome.