version: "3.9"
services:
  ast:
    build: .
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - .:/ffuf
    extra_hosts:
      - "${HOSTNAME}:${CONNECT_TO_IP}"
  grid:
    image: "selenium/standalone-chrome"
    env_file: .env
    ports:
      - "4444:4444"
      # Switch on 7900 if SE_START_XVFB=true 
      #- "7900:7900"
    shm_size: "2gb"
    extra_hosts:
      - "${HOSTNAME}:${CONNECT_TO_IP}"